### ISSUE TITLE
Overley Verbose CSS in HTML

### ISSUE THREAD

**Issue by daveaccent** [accent-starlette/starlette-admin#2]
I need to simplfy the html as it's getting CSS class heavy, the index page has styles.

**Comment by stuartaccent** [comment]
looks good, there's not too many classes I can see that would be worth merging together, most of the html would be in includes anyway like:
- the raised panels for messages
- breadcrumbs
- tabs prob
- etc

as it all need to be set up from the python side. there won't be tons of files for a user to configure to worry about getting all the classes in. would wait till its all split up and see what we keep repeating
